all: mutex_mut mutex factorial dead_blok
mutex_mut: mutex_mut.c
	gcc mutex_mut.c -pthread -o mutex_mut
mutex: mutex.c
	gcc mutex.c -pthread -o mutex
factorial: factorial.c
	gcc factorial.c -pthread -o factorial
dead_blok: dead_blok.c
	gcc dead_blok.c -pthread -o dead_blok